import { ApiException, fromHono } from "chanfana";
import { Hono } from "hono";
import * as Sentry from "@sentry/cloudflare";
import { ContentfulStatusCode } from "hono/utils/http-status";
import pkg from "../package.json";
import { getOpenApiInfo, getScalarHtml, type AppMeta } from "./app-meta";
import type { Bindings } from "./types";
import { documentsRouter } from "./endpoints/documents/router";
import { jobsRouter } from "./endpoints/jobs/router";
import { internalJobsRouter } from "./endpoints/jobs/internal";

// Start a Hono app
const app = new Hono<{ Bindings: Bindings }>();

const appMeta: AppMeta = {
	name: pkg.name,
	version: pkg.version,
	description: pkg.description,
};

app.onError((err, c) => {
	if (err instanceof ApiException) {
		// If it's a Chanfana ApiException, let Chanfana handle the response
		return c.json(
			{ success: false, errors: err.buildResponse() },
			err.status as ContentfulStatusCode,
		);
	}

	console.error("Global error handler caught:", err); // Log the error if it's not known

	// For other errors, return a generic 500 response
	return c.json(
		{
			success: false,
			errors: [{ code: 7000, message: "Internal Server Error" }],
		},
		500,
	);
});

// Setup OpenAPI registry
const openapi = fromHono(app, {
	// Keep the autogenerated docs available; serve Scalar at `/docsz`.
	docs_url: "/docs",
	schema: {
		info: getOpenApiInfo(appMeta),
	},
});

app.get("/", (c) => {
	if (c.req.header("x-force-error") === "1") {
		throw new Error("Forced error");
	}

	return c.json({ name: appMeta.name, version: appMeta.version });
});

app.get("/healthz", (c) => {
	return c.json({ ok: true });
});

app.get("/docsz", (c) => {
	return c.html(getScalarHtml(appMeta));
});

// Register API routes
openapi.route("/documents", documentsRouter);
openapi.route("/jobs", jobsRouter);

// Internal routes (for worker-to-worker communication)
// These are not exposed in OpenAPI docs
app.route("/internal/jobs", internalJobsRouter);

// Sentry is enabled only when SENTRY_DSN environment variable is set.
// Configure it via wrangler secrets: `wrangler secret put SENTRY_DSN`
export default Sentry.withSentry((env: Bindings) => {
	const { id: versionId } = env.CF_VERSION_METADATA;
	return {
		// When DSN is undefined/empty, Sentry SDK is disabled (no events sent)
		dsn: env.SENTRY_DSN,
		release: versionId,
		environment: env.ENVIRONMENT,
		// Adds request headers and IP for users, for more info visit:
		// https://docs.sentry.io/platforms/javascript/guides/cloudflare/configuration/options/#sendDefaultPii
		sendDefaultPii: true,
	};
}, app);
