import type { Context } from "hono";

/**
 * Document processing job payload for queue
 */
export interface DocumentProcessingJob {
	jobId: string;
	documentId: string;
	organizationId: string;
	originalFileKey: string;
	previewKeys: string[];
	createdBy: string;
}

/**
 * Extended environment bindings with custom properties.
 * The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
 */
export type Bindings = Env & {
	/** D1 Database for documents and jobs */
	DB: D1Database;
	/** R2 Bucket for storing documents and previews */
	R2_BUCKET: R2Bucket;
	/** Queue for document processing jobs */
	DOC_PROCESSING_QUEUE: Queue<DocumentProcessingJob>;
	/** Service binding to auth-svc for worker-to-worker communication */
	AUTH_SERVICE: Fetcher;
	/** Auth service URL for JWKS */
	AUTH_SERVICE_URL?: string;
	/** Auth JWKS cache TTL in seconds */
	AUTH_JWKS_CACHE_TTL?: string;
	/** Environment name */
	ENVIRONMENT?: string;
	/**
	 * Cloudflare Worker version metadata.
	 * Used for Sentry release tracking.
	 */
	CF_VERSION_METADATA: WorkerVersionMetadata;
	/**
	 * Sentry DSN for error tracking.
	 * If not set, Sentry will be disabled.
	 * Configured via Cloudflare Dashboard secrets or wrangler vars.
	 */
	SENTRY_DSN?: string;
};

export type AppContext = Context<{ Bindings: Bindings }>;
export type HandleArgs = [AppContext];
