import type { Context } from "hono";
import type { AuthVariables } from "./middleware/auth";

/**
 * Document types for KYC
 */
export type DocumentType =
	| "mx_ine_front"
	| "mx_ine_back"
	| "passport"
	| "proof_of_address"
	| "proof_of_income"
	| "bank_statement"
	| "utility_bill"
	| "other";

/**
 * Required document with optional label/description
 * Used in upload links to show custom document names
 */
export interface RequiredDocument {
	type: DocumentType;
	label?: string;
	description?: string;
}

/**
 * Upload link status
 */
export type UploadLinkStatus = "active" | "expired" | "completed";

/**
 * SSE Event types for upload link notifications
 */
export type SSEEventType =
	| "connected"
	| "document-initiated"
	| "document-uploaded"
	| "document-confirmed"
	| "link-completed"
	| "ping";

/**
 * SSE Event payload
 */
export interface SSEEvent {
	type: SSEEventType;
	data?: {
		documentId?: string;
		documentType?: string;
		fileName?: string;
		uploadLinkId?: string;
		totalDocuments?: number;
		timestamp?: string;
	};
}

/**
 * Extended environment bindings with custom properties.
 * The base Env is auto-generated by `wrangler types` in worker-configuration.d.ts
 */
export type Bindings = Env & {
	/** D1 Database for documents and upload links */
	DB: D1Database;
	/** R2 Bucket for storing documents */
	R2_BUCKET: R2Bucket;
	/** Durable Object for SSE event broadcasting */
	UPLOAD_LINK_EVENTS: DurableObjectNamespace;
	/**
	 * Service binding to auth-svc via `AuthSvcEntrypoint`.
	 * Caller wrangler config must include `"entrypoint": "AuthSvcEntrypoint"`.
	 */
	AUTH_SERVICE: { getJwks(): Promise<{ keys: unknown[] }> };
	/** Auth service URL for JWKS */
	AUTH_SERVICE_URL?: string;
	/** Auth JWKS cache TTL in seconds */
	AUTH_JWKS_CACHE_TTL?: string;
	/** Environment name */
	ENVIRONMENT?: string;
	/**
	 * Cloudflare Worker version metadata.
	 * Used for Sentry release tracking.
	 */
	CF_VERSION_METADATA: WorkerVersionMetadata;
	/**
	 * Sentry DSN for error tracking.
	 * If not set, Sentry will be disabled.
	 * Configured via Cloudflare Dashboard secrets or wrangler vars.
	 */
	SENTRY_DSN?: string;

	// R2 S3 API credentials for presigned URLs
	/** Cloudflare Account ID for R2 */
	R2_ACCOUNT_ID?: string;
	/** R2 API Access Key ID */
	R2_ACCESS_KEY_ID?: string;
	/** R2 API Secret Access Key */
	R2_SECRET_ACCESS_KEY?: string;
	/** R2 Bucket Name */
	R2_BUCKET_NAME?: string;
	/** R2 Public Custom Domain (e.g., doc-storage-dev.janovix.com) */
	R2_PUBLIC_DOMAIN?: string;

	// Turnstile configuration for public uploads
	/** Cloudflare Turnstile Secret Key */
	TURNSTILE_SECRET_KEY?: string;

	// Session token signing
	/** Secret for signing session tokens */
	SESSION_TOKEN_SECRET?: string;

	// CORS configuration
	/** Comma-separated list of trusted origin patterns for CORS */
	TRUSTED_ORIGINS?: string;
};

export type AppContext = Context<{
	Bindings: Bindings;
	Variables: AuthVariables;
}>;
export type HandleArgs = [AppContext];
